### ISSUE TITLE
Cliff texture is very metallic/shiny

### ISSUE THREAD

**Issue by LeonStansfield** [radiatoryang/unity-triplanar-terrain-cliff-shader#6]
THe cliff texture is very metallic, no matter the metallicness or smoothness of the texture applied, leading to odd spectral highlights on what is supposed to be (in my case) a rough texture

**Comment by LeonStansfield** [comment]
![Capture](https://user-images.githubusercontent.com/23266792/143301232-f3c6d863-cf45-4b4e-9b80-97e777340393.PNG)
I have tried this with other textures including the 'terrain textures pack free' asset pack from the unity asset store, with the included normal maps.

**Comment by radiatoryang** [comment]
@LeonStansfield you should edit the smoothness hack directly in the shader code... currently the shader just does weird stuff with the red channel of the cliff albedo

https://github.com/radiatoryang/unity-triplanar-terrain-cliff-shader/blob/02be881bd78657431fd374096b9a28ad76642d9f/Terrain-TriplanarStandard-FirstPass.shader#L88-L90

it is already set to use 0% metallic

e.g. for 0% smoothness on cliffs, replace line 88 above with --
`o.Smoothness = lerp(0, o.Smoothness, threshold);`

**Comment by LeonStansfield** [comment]
Thanks man, first time using shaders I thought it would be something as simple as that.
